services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_SOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/zen_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
volumes:
  data-volume: